name: Deployment Pipeline
on:
  push:
    branches: 
      - "manhpv"
  pull_request:
    branches: 
      - "dev"

jobs:
  build-algorithm-service:
    name: Build algorithm service
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata for the Docker image
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ vars.REGISTRY }}/${{ vars.ALGO_SERVICE_IMAGE }}

      - name: Passing ConnectionString to Appsettings.Production.json
        run: |
          echo "$(jq '.ConnectionStrings.DB = "Server=${{ secrets.SQL_DATABASE_HOST }};Database=${{ secrets.SQL_DATABASE_NAME }};User Id=${{ secrets.SQL_DATABASE_USERNAME }};Password=${{ secrets.SQL_DATABASE_PASSWORD }}; TrustServerCertificate=True"' AlgorithmService/appsettings.Production.json)" > AlgorithmService/appsettings.Production.json

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: "AlgorithmService/Dockerfile"
          push: true
          tags: ${{ vars.REGISTRY }}/${{ vars.ALGO_SERVICE_IMAGE }}:${{ github.sha }}
          labels: ${{ steps.meta.outputs.labels }}

  build-backend-service:
    name: Build backend service
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Check file exited
        run: |
          cat "JiraSchedulingConnectAppService/appsettings.Production.json"
      - name: Passing ConnectionString to Appsettings.Production.json
        run: |
          echo "$(jq '.ConnectionStrings.DB = "Server=${{ secrets.SQL_DATABASE_HOST }};Database=${{ secrets.SQL_DATABASE_NAME }};User Id=${{ secrets.SQL_DATABASE_USERNAME }};Password=${{ secrets.SQL_DATABASE_PASSWORD }}; TrustServerCertificate=True"' JiraSchedulingConnectAppService/appsettings.Production.json)" > JiraSchedulingConnectAppService/appsettings.Production.json

      - name: Extract metadata for the Docker image
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ vars.REGISTRY }}/${{ vars.BE_SERVICE_IMAGE }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: "JiraSchedulingConnectAppService/Dockerfile"
          push: true
          tags: ${{ vars.REGISTRY }}/${{ vars.BE_SERVICE_IMAGE }}:${{ github.sha }}
          labels: ${{ steps.meta.outputs.labels }}
  
  build-admin-webapp:
    name: Build Admin Webapp service
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata for the Docker image
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ vars.REGISTRY }}/${{ vars.ADMIN_WEBAPP_IMAGE }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: "ResourceAssignAdmin/Dockerfile"
          push: true
          tags: ${{ vars.REGISTRY }}/${{ vars.ADMIN_WEBAPP_IMAGE }}:${{ github.sha }}
          labels: ${{ steps.meta.outputs.labels }}


  build-gateway-service:
    name: Build Gateway service
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata for the Docker image
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ vars.REGISTRY }}/gateway_service

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: GatewayAppService/.
          file: "GatewayAppService/Dockerfile"
          push: true
          tags: ${{ vars.REGISTRY }}/gateway_service:${{ github.sha }}
          labels: ${{ steps.meta.outputs.labels }}


  test-intergrate-service:
    name: Test service run success
    runs-on: ubuntu-latest
    needs: [build-algorithm-service, build-backend-service, build-admin-webapp, build-gateway-service]
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      
      - name: Test the Docker image
        run: BACKEND_IMAGE_TAG=${{ github.sha }}  ALGO_IMAGE_TAG=${{ github.sha }} WEBAPP_IMAGE_TAG=${{ github.sha }} GATEWAY_IMAGE_TAG=${{ github.sha }} docker-compose -f docker-compose.deployment.yml up -d

  deploy-service:
    name: Deploy services to Server
    runs-on: ubuntu-latest
    needs: [build-algorithm-service, build-backend-service, test-intergrate-service, build-admin-webapp]

    steps:
      - name: install ssh keys
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
        
      - name: Connect & Pull & Deploy
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }} && git checkout $(git rev-parse --abbrev-ref HEAD) && git pull && sudo BACKEND_IMAGE_TAG=${{ github.sha }}  ALGO_IMAGE_TAG=${{ github.sha }} WEBAPP_IMAGE_TAG=${{ github.sha }} GATEWAY_IMAGE_TAG=${{ github.sha }} docker-compose -f docker-compose.deployment.yml up -d && sudo docker image prune -a --force && exit"
      
      - name: cleanup
        run: rm -rf ~/.ssh


  # push_to_registry:
  #   name: Push Docker image to Docker Hub
  #   runs-on: ubuntu-latest
  #   needs: [build, test]
  #   if: always()

  #   steps:
  #     - name: Check out the repo
  #       uses: actions/checkout@v3

  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v2

  #     - name: Log in to Docker Hub
  #       uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
  #       with:
  #         username: pham2604
  #         password: PhamManh@2604

  #     - name: Extract metadata (tags, labels) for Docker
  #       id: meta
  #       uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
  #       with:
  #         images: ${{ env.REGISTRY }}/${{ env.BE_SERVICE_IMAGE }}

  #     - name: Build and push Docker image
  #       uses: docker/build-push-action@v2
  #       with:
  #         context: "{{defaultContext}}"
  #         push: true
  #         tags: ${{ steps.meta.outputs.tags }}
  #         labels: ${{ steps.meta.outputs.labels }}
      
    
